version: "0.1"

services:
  report:
    image: report
    container_name: report
    restart: unless-stopped
    ports:
      - 8080:8080

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /tmp/data/db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
# services:

#   counter:
#     image: gcr.io/${PROJECT_ID}/gcb-docker-compose:latest
#     container_name: counter
#     depends_on:
#       - redis
#     ports:
#       - "50051:50051"
#     environment:
#       - REDIS_HOST=redis
#       - REDIS_PORT=6379

#   redis:
#     image: redis
#     ports:
#       - "6379:6379"
